### ISSUE TITLE
What's the plugin on the left side of your screenshot?

### ISSUE THREAD

**Issue by chuyik** [EliverLara/juicy-syntax#1]
![image](https://cloud.githubusercontent.com/assets/6262943/12711528/adce2580-c8fb-11e5-8177-e9268bd9e5eb.png)

Hi I'm a curious about this layout, have you used some plugin to make it?

**Comment by EliverLara** [comment]
Hi, the plugin is [tool-bar](https://github.com/suda/tool-bar)

**Comment by chuyik** [comment]
Yeeaah thanks man!
